CREATE DATABASE yeticave
    DEFAULT CHARACTER SET utf8
    DEFAULT COLLATE UTF8_GENERAL_CI;

USE yeticave;

CREATE TABLE categories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    code VARCHAR(64) NOT NULL

CREATE UNIQUE INDEX name_udx ON categories(name);

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    creation_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    email  VARCHAR(128) NOT NULL UNIQUE,
    name VARCHAR(64) NOT NULL,
    password VARCHAR(64) NOT NULL,
    contacts VARCHAR(255) NOT NULL
);

CREATE INDEX name_idx ON users(name);

CREATE TABLE lots (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    creation_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_time DATETIME NOT NULL,
    description TEXT,
    image_link VARCHAR(128),
    starting_price INT UNSIGNED NOT NULL,
    step_bid INT UNSIGNED NOT NULL,
    user_id INT NOT NULL,
    winner_id INT,
    category_id INT NOT NULL
);

CREATE TABLE bid (
    id INT AUTO_INCREMENT PRIMARY KEY,
    creation_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    value INT NOT NULL,
    user_id INT NOT NULL,
    lot_id INT NOT NULL
);

CREATE INDEX lot ON lots(name);
